/**:
  ros__parameters:
    model:
      repo: unsloth/Qwen3.5-4B-GGUF
      filename: Qwen3.5-4B-Q4_K_M.gguf
    mmproj:
      repo: unsloth/Qwen3.5-4B-GGUF
      filename: mmproj-F32.gguf

    context:
      n_ctx: 16384
      n_batch: 1024
      n_predict: 2000

    gpu:
      n_gpu_layers: -1

    cpu:
      n_threads: -1

    prompt:
      stopping_words:
      - "eot_id"
      - "<|im_end|>"
      - "<|end|>"
      - "<|im_start|>"
      - "<|endoftext|>"

    lora:
      adapters:
      - gpsr

      gpsr:
        repo: unileon-robotics/Qwen3.5-4B-GPSR-LoRA-GGUF
        filename: f32.gguf
        scale: 0.7
